# Generated by Django 2.2.5 on 2020-02-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awteam_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['awteam_name'],
            },
        ),
        migrations.CreateModel(
            name='Operative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Please enter an email, max 200 characters', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('intel', 'Gather intel'), ('retrieve', 'Retrieve'), ('lockdown', 'Lock down area'), ('rescue', 'Rescue target')], default='intel', max_length=2)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('end_date', models.DateTimeField(verbose_name='date finished')),
                ('notes', models.TextField()),
                ('awteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamoperation.AWTeam')),
            ],
            options={
                'ordering': ['mission_name'],
            },
        ),
        migrations.AddField(
            model_name='awteam',
            name='op_team',
            field=models.ManyToManyField(to='teamoperation.Operative'),
        ),
    ]
