# Generated by Django 2.2.5 on 2020-02-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamoperation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='awteam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teamoperation.AWTeam'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('intel', 'Gather intel'), ('retrieve', 'Retrieve'), ('lockdown', 'Lock down area'), ('rescue', 'Rescue target')], default='intel', max_length=20),
        ),
    ]
